dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install pylint
  - pip install flake8
  - pip install pytest --upgrade
script:
  - pylint *.py
  - flake8 *.py
  - pytest
