language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install pylint
  - pip install pytest --upgrade
script:
  # Only run pylint on Python 2 instances, because of the unicode() call
  - if [[ $(python --version) < "Python 3" ]]; then pylint *.py; fi
  - pytest