on: [push, pull_request]

name: CI

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.7', '3.7', '3.8', '3.9', '3.10', '3.11' ]
        include:
          - python-version: '3.7'
            disable: '--disable=consider-using-f-string'
          - python-version: '3.8'
            disable: '--disable=consider-using-f-string,redundant-u-string-prefix'
          - python-version: '3.9'
            disable: '--disable=consider-using-f-string,redundant-u-string-prefix'
          - python-version: '3.10'
            disable: '--disable=consider-using-f-string,redundant-u-string-prefix'
          - python-version: '3.11'
            disable: '--disable=consider-using-f-string,redundant-u-string-prefix'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint flake8 pytest
      - name: Lint with pylint
        run: pylint ${{ matrix.disable }} *.py
      - name: Lint with flake8
        run: flake8 *.py
      - name: Test with pytest
        run: pytest
